Postage OpenSSL

diff --git a/postage/configure b/postage/configure
--- a/postage/configure
+++ b/postage/configure
@@ -53,126 +53,88 @@ MAKE="make"
 MANDIR="share\/man"
 printf "checking for platform..."
 if test $(uname -s) = "Linux"; then
-	LDFLAGS="-lpq -lm -lrt"
+	LDFLAGS="-lm -lrt"
 	CPPFLAGS="-D_GNU_SOURCE"
 	echo "Linux"
 
-	# On linux it is easy to check for libressl
-	printf "checking for LibTLS..."
-	if test $(ldconfig -p | grep "libtls.so " | wc -l) = "1"; then
-		libtls="use"
-		echo "yes"
-	else
+	printf "checking for OpenSSL..."
+	command -v openssl >/dev/null 2>&1 || {
 		echo "no"
-	fi
-	ARC4RANDOM="linux"
+		echo >&2 "OpenSSL not found! Install it and re-run configure."
+		exit 1
+	}
+	echo "yes"
+
 elif test $(uname -s) = "Darwin"; then
-	LDFLAGS="-L\/usr\/local\/lib -lpq -lm -L\/usr\/local\/opt\/gettext\/lib"
-	CPPFLAGS="-I\/usr\/local\/opt\/gettext\/include"
+	LDFLAGS="-lm"
 	echo "Darwin"
-	ARC4RANDOM="osx"
+
+	printf "checking for OpenSSL..."
+	command -v openssl >/dev/null 2>&1 || {
+		echo "no"
+		echo >&2 "OpenSSL not found! Install it and re-run configure."
+		exit 1
+	}
+	echo "yes"
+
 elif test $(uname -s) = "FreeBSD"; then
-	LDFLAGS="-lpq -lm -lintl"
+	LDFLAGS="-lm -lintl"
 	MAKE=gmake
 	MANDIR="man"
 	echo "FreeBSD"
-	ARC4RANDOM="freebsd"
+
+	printf "checking for OpenSSL..."
+	command -v openssl >/dev/null 2>&1 || {
+		echo "no"
+		echo >&2 "OpenSSL not found! Install it and re-run configure."
+		exit 1
+	}
+	echo "yes"
+
 elif test $(uname -s) = "OpenBSD"; then
-	LDFLAGS="-lpq -lm -lintl"
+	LDFLAGS="-lm -lintl"
 	CPPFLAGS=""
 	MAKE=gmake
 	MANDIR="man"
 	echo "OpenBSD"
 
-	printf "checking for LibTLS..."
-	libtls="use"
-	echo "yes"
 else
-	LDFLAGS="-lpq -lm"
+	LDFLAGS="-lm"
 	echo "Unknown"
+
+	printf "checking for OpenSSL..."
+	command -v openssl >/dev/null 2>&1 || {
+		echo "no"
+		echo >&2 "OpenSSL not found! Install it and re-run configure."
+		exit 1
+	}
+	echo "yes"
+
 fi
 
-LDFLAGS="$LDFLAGS -L$(pg_config --libdir)"
+#### LIBPQ
+LDFLAGS="$LDFLAGS -L$(pg_config --libdir) -lpq"
 CPPFLAGS="$CPPFLAGS -I$(pg_config --includedir)"
 
-BUILD_DEPS=""
+#### OPENSSL
+OPENSSL_PATH=$(command -v openssl)
+SSL_INCLUDEDIR="${OPENSSL_PATH%bin/openssl}include"
 
-#### CHECK LIBRESSL VERSION
-## if we have libressl, we need to check for 2.3.2 or newer (the api changed slightly)
-if test $libtls = "use"; then
-	printf "checking for LibTLS version >= 2.3.2..."
-	# check LibreSSL version
-	has_good_libressl=$(openssl version | awk ' { split($2,a,"."); print (a[1] > 1) && (a[2] > 2) && (a[2] > 3 || a[3] > 1) } ')
-	if test "x$has_good_libressl" = "x1"; then
-		libtls="use"
-		echo "yes"
-	else
-		libtls="build"
-		echo "no"
-	fi
+CHECK_CPPFLAGS="-I$SSL_INCLUDEDIR"
+HEADER="openssl/ssl.h"
+. scripts/check_header
+if test "x$HAVE_HEADER" = "x0"; then
+	echo >&2 "Cannot use openssl/ssl.h! Install the OpenSSL headers and re-run configure."
+	exit 1
 fi
 
-if test $libtls = "build"; then
-	WHICH_SSL=$(which openssl)
-	SSL_INCLUDEDIR="${WHICH_SSL%bin/openssl}include"
-	CPPFLAGS="$CPPFLAGS -I$SSL_INCLUDEDIR -DLIBRESSL_INTERNAL -D__BEGIN_HIDDEN_DECLS= -D__END_HIDDEN_DECLS= -DSSL_OP_NO_CLIENT_RENEGOTIATION=0x00020000L -DX509_V_FLAG_NO_CHECK_TIME=0x200000 -DSSL_CTRL_SET_DH_AUTO=118 -DX509_L_MEM=3"
-	SSL_LIBDIR="${WHICH_SSL%bin/openssl}lib"
-	LDFLAGS="$LDFLAGS -L$SSL_LIBDIR ../dependencies/libtls/libtls.a -lssl -lcrypto"
-
-	FUNCTION="getentropy"
-	. scripts/check_function
-	CUR_FUNCTION_VAR_NAME="HAVE_"$(echo "$FUNCTION" | tr '[a-z]' '[A-Z]')
-	CPPFLAGS="$CPPFLAGS -D$CUR_FUNCTION_VAR_NAME""=$HAVE_FUNCTION"
-	if test "x$HAVE_FUNCTION" != "x1"; then
-		COMPAT="$COMPAT ../dependencies/libtls/compat/getentropy_${ARC4RANDOM}.c"
-	fi
-
-	FUNCTION="arc4random"
-	. scripts/check_function
-	CUR_FUNCTION_VAR_NAME="HAVE_"$(echo "$FUNCTION" | tr '[a-z]' '[A-Z]')
-	CPPFLAGS="$CPPFLAGS -D$CUR_FUNCTION_VAR_NAME""=$HAVE_FUNCTION"
-	if test "x$HAVE_FUNCTION" != "x1"; then
-		COMPAT="$COMPAT ../dependencies/libtls/compat/arc4random.c"
-	fi
-
-	FUNCTION="asprintf"
-	. scripts/check_function
-	CUR_FUNCTION_VAR_NAME="HAVE_"$(echo "$FUNCTION" | tr '[a-z]' '[A-Z]')
-	CPPFLAGS="$CPPFLAGS -D$CUR_FUNCTION_VAR_NAME""=$HAVE_FUNCTION"
-	if test "x$HAVE_FUNCTION" != "x1"; then
-		COMPAT="$COMPAT ../dependencies/libtls/compat/bsd-asprintf.c"
-	fi
-
-	CHECK_FUNCTIONS="explicit_bzero getpagesize inet_pton reallocarray recallocarray strcasecmp strlcat strlcpy strndup strnlen strsep timegm timingsafe_bcmp timingsafe_memcmp"
-	for FUNCTION in $CHECK_FUNCTIONS; do
-		. scripts/check_function
-		CUR_FUNCTION_VAR_NAME="HAVE_"$(echo "$FUNCTION" | tr '[a-z]' '[A-Z]')
-		CPPFLAGS="$CPPFLAGS -D$CUR_FUNCTION_VAR_NAME""=$HAVE_FUNCTION"
-		if test "x$HAVE_FUNCTION" != "x1"; then
-			COMPAT="$COMPAT ../dependencies/libtls/compat/${FUNCTION}.c"
-		fi
-	done
-
-	CHECK_CPPFLAGS="-I$SSL_INCLUDEDIR"
-	HEADER="openssl/ssl.h"
-	. scripts/check_header
-	if test "x$HAVE_HEADER" != "x1"; then
-		echo "Could not find OpenSSL headers! Install them and re-run configure."
-		exit 1
-	fi
-	BUILD_DEPS="$BUILD_DEPS libtls"
-elif test $libtls = "use"; then
-	WHICH_SSL=$(which openssl)
-	SSL_LIBDIR="${WHICH_SSL%bin/openssl}lib"
-	LDFLAGS="$LDFLAGS $SSL_LIBDIR/libtls.a $SSL_LIBDIR/libssl.a $SSL_LIBDIR/libcrypto.a"
-fi
+CPPFLAGS="$CPPFLAGS -I$SSL_INCLUDEDIR"
+LDFLAGS="$LDFLAGS -lssl -lcrypto"
 
 #### LIBEV
 
 USE_LRT="no"
 libev_CPPFLAGS=""
-LDFLAGS="$LDFLAGS ev.o"
-BUILD_DEPS="$BUILD_DEPS ev.o"
 CHECK_HEADERS="sys/inotify.h sys/epoll.h sys/event.h port.h poll.h sys/select.h sys/eventfd.h sys/signalfd.h"
 for HEADER in $CHECK_HEADERS; do
 	. scripts/check_header
@@ -313,7 +275,6 @@ echo "$has_new_sock_directory_parameter_postgres"
 sed -e "s|@sock_dir_parameter@|$directory_parameter|g" \
 	-e "s|@LDFLAGS@|$LDFLAGS|g" \
 	-e "s|@CPPFLAGS@|$CPPFLAGS|g" \
-	-e "s|@BUILD_DEPS@|$BUILD_DEPS|g" \
 	-e "s|@prefix@|$PREFIX|g" \
 	-e "s|@MANDIR@|$MANDIR|g" \
 	-e "s|@libev_CPPFLAGS@|$libev_CPPFLAGS|g" \
